export const images = {
  headerIcon: require('./images/header-icon.png'),
  post1: require('./images/post1.jpg'),
  post2: require('./images/post2.jpg'),
  post3: require('./images/post3.jpg'),
  post4: require('./images/post4.jpg'),
  post5: require('./images/post5.jpg'),
  post6: require('./images/post6.jpg'),
  post7: require('./images/post7.jpg'),
  post8: require('./images/post8.jpg'),
  profile1: require('./images/profile1.jpg'),
  profile2: require('./images/profile2.jpg'),
  profile3: require('./images/profile3.jpg'),
  doobrySuccess: require('./images/doobry-success.png'),
};
